### ISSUE TITLE
layout pengaturan profile user

### ISSUE THREAD

**Issue by satriyoaji** [tesu-tesu/antrian-sehat-android#73]

**Comment by tesu-tesu** [comment]
![image](https://user-images.githubusercontent.com/72516106/100421445-f8bb3200-30ba-11eb-967d-f9f766fa3b3a.png)

**Comment by tesu-tesu** [comment]
![image](https://user-images.githubusercontent.com/72516106/100421529-1b4d4b00-30bb-11eb-94a3-074a33b1a990.png)

**Comment by tesu-tesu** [comment]
![image](https://user-images.githubusercontent.com/72516106/100421586-3a4bdd00-30bb-11eb-8d52-1212b70d7e0e.png)
